source "https://rubygems.org"

# Dépendance principale pour configurer GitHub Pages avec Jekyll
gem "github-pages", "~> 229", group: :jekyll_plugins

# Thème par défaut pour Jekyll
gem "minima", "~> 2.5"

# Plugins spécifiques pour Jekyll (utilisés dans les configurations de GitHub Pages)
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12" # Génère automatiquement des flux RSS
end

# Configuration pour les environnements Windows
platforms :mingw, :x64_mingw, :mswin, :jruby do
  # Gestion des fuseaux horaires pour Windows
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Amélioration des performances pour la surveillance des fichiers sur Windows
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]

# Spécifique à JRuby : compatibilité avec la bibliothèque http_parser.rb
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]

# Serveur web pour exécuter Jekyll en local (nécessaire pour Ruby 3.0+)
gem "webrick", "~> 1.8"
